export { FoodCategory, FoodCategorySchema, ANIMAL_PROTEIN_CATEGORIES } from './foodCategory'
export type { FoodCategory as FoodCategoryType } from './foodCategory'
export { TrafficLightColor, TrafficLightColorSchema } from './trafficLight'
export type { TrafficLightColor as TrafficLightColorType } from './trafficLight'
export { FoodSchema, food } from './food'
export type { Food } from './food'
